# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'frontgui.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_BarbieWithBrain(object):
    def setupUi(self, BarbieWithBrain):
        BarbieWithBrain.setObjectName("BarbieWithBrain")
        BarbieWithBrain.resize(912, 697)
        self.centralwidget = QtWidgets.QWidget(BarbieWithBrain)
        self.centralwidget.setObjectName("centralwidget")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(0, 0, 921, 671))
        self.label.setText("")
        self.label.setPixmap(QtGui.QPixmap("C:/Users/LENOVO/Downloads/2RNb.gif"))
        self.label.setScaledContents(True)
        self.label.setObjectName("label")
        self.pushButton = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton.setGeometry(QtCore.QRect(670, 630, 93, 28))
        font = QtGui.QFont()
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.pushButton.setFont(font)
        self.pushButton.setStyleSheet("background-color: rgb(0, 0, 127);\n"
"background-color: rgb(0, 255, 255);")
        self.pushButton.setObjectName("pushButton")
        self.pushButton_2 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_2.setGeometry(QtCore.QRect(770, 630, 91, 28))
        font = QtGui.QFont()
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.pushButton_2.setFont(font)
        self.pushButton_2.setStyleSheet("background-color: rgb(255, 38, 49);")
        self.pushButton_2.setObjectName("pushButton_2")
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_2.setGeometry(QtCore.QRect(20, 20, 371, 81))
        self.label_2.setText("")
        self.label_2.setPixmap(QtGui.QPixmap("C:/Users/LENOVO/Downloads/Jarvis_Loading_Screen.gif"))
        self.label_2.setObjectName("label_2")
        self.textBrowser = QtWidgets.QTextBrowser(self.centralwidget)
        self.textBrowser.setGeometry(QtCore.QRect(440, 30, 201, 51))
        font = QtGui.QFont()
        font.setPointSize(16)
        font.setBold(True)
        font.setWeight(75)
        self.textBrowser.setFont(font)
        self.textBrowser.setStyleSheet("background:transparent;\n"
"border-radius:none;\n"
"color:white;\n"
"font-size:20px;")
        self.textBrowser.setObjectName("textBrowser")
        self.textBrowser_2 = QtWidgets.QTextBrowser(self.centralwidget)
        self.textBrowser_2.setGeometry(QtCore.QRect(660, 30, 201, 51))
        font = QtGui.QFont()
        font.setPointSize(16)
        font.setBold(True)
        font.setWeight(75)
        self.textBrowser_2.setFont(font)
        self.textBrowser_2.setStyleSheet("background:transparent;\n"
"border-radius:none;\n"
"color:white;\n"
"font-size:20px;")
        self.textBrowser_2.setObjectName("textBrowser_2")
        BarbieWithBrain.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(BarbieWithBrain)
        self.statusbar.setObjectName("statusbar")
        BarbieWithBrain.setStatusBar(self.statusbar)

        self.retranslateUi(BarbieWithBrain)
        QtCore.QMetaObject.connectSlotsByName(BarbieWithBrain)

    def retranslateUi(self, BarbieWithBrain):
        _translate = QtCore.QCoreApplication.translate
        BarbieWithBrain.setWindowTitle(_translate("BarbieWithBrain", "MainWindow"))
        self.label.setStyleSheet(_translate("BarbieWithBrain", "background:transparent;\n"
"border-radius:none;"))
        self.pushButton.setText(_translate("BarbieWithBrain", "Run"))
        self.pushButton_2.setText(_translate("BarbieWithBrain", "Exit"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    BarbieWithBrain = QtWidgets.QMainWindow()
    ui = Ui_BarbieWithBrain()
    ui.setupUi(BarbieWithBrain)
    BarbieWithBrain.show()
    sys.exit(app.exec_())
